apiVersion: v1
kind: Pod
metadata:
  name: pvc-debug
spec:
  containers:
  - name: debug
    image: ubuntu:22.04
    command: ["sleep", "infinity"]
    volumeMounts:
    - name: jobs-storage
      mountPath: /mnt/jobs

  volumes:
  - name: jobs-storage
    persistentVolumeClaim:
      claimName: jobs-pvc

  restartPolicy: Never