apiVersion: batch/v1
kind: Job
metadata:
  name: job-nlp-classifier2

spec:
  backoffLimit: 1

  template:
    spec:
      restartPolicy: Never

      containers:
      - name: classifier
        image: codebyte17/jobs-recommendations:latest2

        resources:
          requests:
            memory: "16Gi"
            cpu: "8"
            nvidia.com/gpu: 1

          limits:
            memory: "32Gi"
            cpu: "16"
            nvidia.com/gpu: 1

        volumeMounts:
          - name: output-volume
            mountPath: /output

      volumes:
        - name: output-volume
          persistentVolumeClaim:
            claimName: jobs-pvc